apiVersion: v1
kind: ServiceAccount
metadata:
  name: smart-proxy-sa
  namespace: test-namespace # The namespace you are installing into
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: smart-proxy-role
  namespace: test-namespace
rules:
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: smart-proxy-binding
  namespace: test-namespace
subjects:
  - kind: ServiceAccount
    name: smart-proxy-sa
roleRef:
  kind: Role
  name: smart-proxy-role
  apiGroup: rbac.authorization.k8s.io
