apiVersion: v1
kind: Service
metadata:
  name: smart-proxy
  namespace: smart-proxy
  labels:
    app: smart-proxy
spec:
  selector:
    app: smart-proxy
  ports:
    - name: proxy
      port: 80
      targetPort: 8080
    - name: admin
      port: 8081
      targetPort: 8081
  type: ClusterIP
